langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: AIzaSyCzagb2Z4azIWluJz9b9q-fxPlm6yuro6M
  app: fathomless-beyond-33278
  run: rails db:migrate
