langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: wfmFmLC1o+4NFLzqikmetCIrTdZopqjcSpbfMvaWyltQIO65rHi91DeHFPAApbeJzMt/3IIqbFJrIX4ZbNT00bl55CE/KY5REy1pDh6libjbM7h36MHL5wlGrPMwufK6WPdv1l90gvCn5M8VlVwLJIj0t22CKRYIJmB5DCYBfydpOQtQ5B5IHnd48ZbWrNfJS+Crp5yDIsByX1JqZMjGW+SOHnGRWr+O+J45KGb1vmx5FhX2fdMIHDvjiL2DoXeedTSAwZ0tHw4VXGM2C3tHcMGmuC5IPV+naJ03VGRzzZbisaMiW6sbn5oJ5t32oaImgLEIo/n3W6Yr1/w/LUOXC9xKeu55kPC0VnNdyk8PNUVRBT26WFyR7HKIa7epxaCLk5suLnHoa51E7m3qZJ1ok3Vw81Ch+TVE6LT311qGvTmdSHqc3Ubpx1yX000KCRH1mpaeEP7NR1D7YVJaYTM0qaWUl2ThbxrzIACVION15X7OcyB6270gND1Tcywozmyh8/tsYBbYgCzzkw/h8hXOCcaCcKQOU5cEzh81os+GKn56+qYOGm8echfux9d4Y2UDaWkeG85H/j8FmQJ88dm3SWtGPURpwaLARa0wAfmmdLH8LRCkXFf3VaeueymyUPXhAReNH0GWp7Bgv1cbEJb5YHa/7zLa9aEdnqfisZMDlas=
  app: fathomless-beyond-33278
  run: rails db:migrate
