langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
  app: fathomless-beyond-33278
  run: rails db:migrate
